
if(CMAKE_BUILD_TYPE MATCHES "Debug")
    set(BUILD ${PROJECT_NAME}d)
elseif(CMAKE_BUILD_TYPE MATCHES "Release")
    set(BUILD ${PROJECT_NAME})
elseif(CMAKE_BUILD_TYPE MATCHES "RelWithDebInfo ")
    set(BUILD ${PROJECT_NAME}rd)
elseif(CMAKE_BUILD_TYPE MATCHES "MinSizeRel ")
    set(BUILD ${PROJECT_NAME}mr)
else()
    set(BUILD ${PROJECT_NAME})
endif()

macro(use_cxx11)
    if (CMAKE_VERSION VERSION_LESS "3.1")
        if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            set (CMAKE_CXX_FLAGS "-std=gnu++11 ${CMAKE_CXX_FLAGS}")
        endif ()
    else ()
        set (CMAKE_CXX_STANDARD 11)
    endif ()
endmacro(use_cxx11)

macro(ForSubdir arg...)
    foreach(dirs ${ARGV})
        add_subdirectory(${dirs})
    endforeach()
endmacro()

macro(Findqt5 arg...)
    if (NOT CMAKE_PREFIX_PATH)
        #set(CMAKE_PREFIX_PATH )
    endif()
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTORCC ON)
    find_package(Qt5 COMPONENTS ${ARGV} REQUIRED)

    if(NOT Qt5_FOUND)
        message(FATAL_ERROR "QT not find. you can set CMAKE_PREFIX_PATH!")
    endif()
endmacro(Findqt5)
